# Generated by Django 4.0.6 on 2022-07-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
