# Generated by Django 4.0.6 on 2022-07-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_photo_user_detail_user_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user_detail'),
        ),
    ]
