# Generated by Django 4.0.6 on 2022-07-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_panier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
