# Generated by Django 4.0.6 on 2022-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='taille',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
