# Generated by Django 4.0.6 on 2022-07-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_article_color_article_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='taille',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
