# Generated by Django 4.0.6 on 2022-07-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_alter_article_taille'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='article_name',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='panier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
