# Generated by Django 4.0.6 on 2022-07-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_favorit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='article',
        ),
        migrations.CreateModel(
            name='ArticleInPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=50, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.article')),
                ('panier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.panier')),
            ],
        ),
    ]
