# Generated by Django 4.0.6 on 2022-07-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_panier_article_articleinpanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinpanier',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
