# Generated by Django 4.0.6 on 2022-07-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_articleinpanier_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='panier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.panier'),
        ),
    ]
