# Generated by Django 4.0.6 on 2022-07-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_command_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='product',
        ),
    ]
